//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.Web.Mvc;

    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.Downloads = new HashSet<Download>();
            this.NotesAttachments = new HashSet<NotesAttachment>();
            this.NotesReviews = new HashSet<NotesReview>();
            this.ReportedIssues = new HashSet<ReportedIssue>();
        }
    
        public int ID { get; set; }
        public int SellerID { get; set; }
        public int Status { get; set; }
        public Nullable<int> ActionedBy { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        
        [Required(ErrorMessage ="required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "required")]
        public int CategoryID { get; set; }
        public string DisplayPic { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> NoOfPages { get; set; }
        public string Description { get; set; }
        public string UniversityName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Preview { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
       // public HttpPostedFileBase DisplayImageData { get; set; }
       //public HttpPostedFileBase FileData { get; set; }
        //public SelectList Categorylist { get; set; }
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Download> Downloads { get; set; }
        public virtual ReferenceData ReferenceData { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesAttachment> NotesAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesReview> NotesReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedIssue> ReportedIssues { get; set; }
        //public SelectList Countrylist { get; set; }
        //public SelectList Typelist { get; set; }
       // public IEnumerable<SelectListItem> Category { get; set; }
        //public IEnumerable<SelectListItem> Countries { get; set; }

        //public IEnumerable<SelectListItem> Types { get; set; }
        //public List<SelectListItem>
        [NotMapped] public List<Category> CategoryCollection { get; set; }
        [NotMapped] public List<Country> CountryCollection { get; set; }
        [NotMapped] public List<Type> TypeCollection { get; set; }

       
       [NotMapped]public IPagedList<Note> Inprogressnotes { get; set; }
        [NotMapped] public IPagedList<Note> Publishednotes { get; set; }

    }
}
